-- Settlement.
--
-- The app never touches money. It shows a guest what they owe and where to send
-- it, and it records what evidence exists that they did. Money moves
-- bank-to-bank by DuitNow, between two people, with nothing in the middle.
--
-- Because of that, nothing here can *know* a payment happened. There are only
-- two honest sources of that claim, and the schema keeps them distinct:
--
--   a proof the guest submitted, whose figures were read server-side from the
--   screenshot rather than sent by the client, and
--
--   the payer saying so.
--
-- A row in `payment_proofs` is evidence, not a verdict. `participants.settled_at`
-- is the verdict, and `settled_method` records which of the two produced it.

create table public.payment_proofs (
  id uuid primary key default gen_random_uuid(),
  bill_id uuid not null references public.bills (id) on delete cascade,
  participant_id uuid not null,

  -- Read out of the uploaded screenshot on the server. Never written by a
  -- client: a guest who could set these could mark themselves paid, which is
  -- the trust-destroying bug this whole feature exists to avoid.
  amount_sen integer,
  reference text,
  paid_at timestamptz,
  recipient text,
  bank text,
  confidence text check (confidence in ('high', 'medium', 'low')),

  -- What they owed at the moment they uploaded, so the comparison stays
  -- meaningful even if the bill changes afterwards.
  expected_sen integer not null,
  matched boolean not null default false,
  -- Null when matched. Otherwise why not, for the payer to read.
  mismatch_reason text,

  created_at timestamptz not null default now(),

  foreign key (participant_id, bill_id) references public.participants (id, bill_id) on delete cascade
);

create index payment_proofs_bill_id_idx on public.payment_proofs (bill_id, created_at desc);
create index payment_proofs_participant_idx on public.payment_proofs (participant_id);
-- A reference number should only settle one debt on a bill.
create index payment_proofs_reference_idx on public.payment_proofs (bill_id, reference)
  where reference is not null;

alter table public.payment_proofs enable row level security;

create policy "payment_proofs: owner reads" on public.payment_proofs
  for select to authenticated using (public.owns_bill(bill_id));

create policy "payment_proofs: owner updates" on public.payment_proofs
  for update to authenticated
  using (public.owns_bill(bill_id))
  with check (public.owns_bill(bill_id));

-- A guest sees their own proofs and nobody else's: what somebody else paid, and
-- when, is not their business.
create policy "payment_proofs: guest reads own" on public.payment_proofs
  for select to anon, authenticated
  using (
    public.bill_is_shared(bill_id)
    and public.is_claim_token_holder(participant_id)
  );

-- Deliberately no insert policy for anyone. Proofs are written only by the
-- server, after it has read the figures out of the image itself.
revoke insert, update, delete on public.payment_proofs from anon;

-- ---------------------------------------------------------------------------
-- Who the guest is paying
-- ---------------------------------------------------------------------------
-- `profiles` is owner-only, and stays that way. A guest holding the link needs
-- exactly three facts about the payer and gets nothing else -- not their email,
-- not their id, not their other bills.

create or replace function public.get_payee(p_share_token text)
returns table (display_name text, duitnow_mobile text, duitnow_qr_path text)
language sql
stable
security definer
set search_path = ''
as $$
  select p.display_name, p.duitnow_mobile, p.duitnow_qr_path
    from public.bills b
    join public.profiles p on p.id = b.owner_id
   where b.share_token = p_share_token;
$$;

revoke all on function public.get_payee(text) from public;
grant execute on function public.get_payee(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Storage for the payer's DuitNow QR
-- ---------------------------------------------------------------------------
-- A personal DuitNow QR cannot be generated by this app -- it comes out of the
-- payer's own banking app -- so they upload a screenshot of theirs once.
--
-- The bucket is private. Guests never read it directly; the server hands out a
-- short-lived signed URL when it renders the settlement screen.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'duitnow-qr',
  'duitnow-qr',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

create policy "duitnow-qr: owner reads own"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'duitnow-qr'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "duitnow-qr: owner uploads own"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'duitnow-qr'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "duitnow-qr: owner replaces own"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'duitnow-qr'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy "duitnow-qr: owner deletes own"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'duitnow-qr'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

-- ---------------------------------------------------------------------------
-- Announce settlement changes over the bill's channel
-- ---------------------------------------------------------------------------
-- So a guest watching the settlement screen sees the payer confirm them without
-- having to refresh, and the payer sees a proof arrive.

create trigger payment_proofs_broadcast
after insert or update or delete on public.payment_proofs
for each row execute function public.broadcast_bill_change();
